
import { Inter } from "next/font/google";
import { ThemeModeScript } from "flowbite-react";
import "./globals.css";
import { NavbarComponent } from "@/app/components/Navbar";
import { FooterComponent } from "@/app/components/Footer";
import SessionWrapper from "@/app/components/SessionWrapper";
import { ToastContainer } from "react-toastify";
const inter = Inter({ subsets: ["latin"] });
import 'react-toastify/dist/ReactToastify.css';

export const metadata = {
  title: "Create Flowbite React",
  description: "Generated by create flowbite react",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <head>
        <ThemeModeScript />
      </head>
      <body className={inter.className}>
        <SessionWrapper>
          <NavbarComponent />
          {children}
          <FooterComponent />
        </SessionWrapper>
        <ToastContainer />
      </body>
    </html>
  );
}
